
# docker/docker-compose.yml
version: '3'

services:
    php-fpm:
        build: docker/php-fpm/
        volumes:
            - ./project/web:/var/www

    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./project/web:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php-fpm
        ports:
            - "8081:80"

